:Author: tienesabor
:Email: tw88712@gmail.com
:Date: 11/04/2022
:Revision: 0.3.0
:License: Public Domain

= Project: {Project}

Arduino Code for DIY RC airplane.  The main feature of the program is that it contains IMU stabilization system.

== Step 1: Installation
You can use it directly with your Arduino IDE. The parameters to adjust are all in the config.h

== Step 2: Assemble the circuit
You will need following modules:
Arduino UNO/pro mini/nano
RF24L01
MPU6050/9250
a 5V to 3.3V LDR
servo (SG90)
motor/inverter/battery (controlled with PWM)

== Step 3: Load the code
Upload the code contained in this sketch on to your board

=== Folder structure
....
 RF_Receive               => Arduino sketch folder
  ├── RF_Receive.ino      => main Arduino file
  ├── config.h            => parameter cnofigeration
  ├── schematics.png      => (optional) an image of the required schematics. Will update later.
  ├── layout.png          => (optional) an image of the layout. Will update later.
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact tienesabor tw88712@gmail.com

=== BOM
Add the bill of the materials you need for this project.
Please see Step 2
|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
